"""Add role to users

Revision ID: faa83f3f4d3d
Revises: 7428db9f164c
Create Date: 2026-09-07 15:07:52.996130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa83f3f4d3d'
down_revision: Union[str, Sequence[str], None] = '7428db9f164c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'role',
        sa.String(length=50),
        nullable=False,
        server_default='employee',
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
